#' Generate new data based on clusters
#' 
#' This function generates a new dataframe based on clusters generated by the function "divHier()" (or in the same format), 
#' it can be generated by the sum or the mean of the rows that are in the same cluster.
#' 
#' @param data Your data
#' @param cluster Name of the cluster column
#' @param method Method applied to generate the new data based on clusters (mean or sum)
#' 
#' @return It returns a new dataframe generated based on the clusters
#' 

gen_new_data<-function(data,cluster="clusters",method=c("mean","sum")){
  if(length(data)==2){
    data_au<-rbind(data[[1]],data[[2]])
  }
  else{
    data_au<-rbind(data[[1]],data[[2]])
    for (i in 3:length(data)) {
      data_au<-rbind(data_au,data[[i]])
    } 
  }
  
  n<-ncol(data_au)-1
  
  cluster_idx<-unique(data_au[,cluster])
  list_m_clus<-list()
  
  if(method=="mean"){
    for (i in 1:length(cluster_idx)) {
      x<-data_au[data_au[,cluster]==cluster_idx[i],]
      x$clusterXtp<-NULL
      m<-colMeans(x[,1:n])
      list_m_clus[[i]]<-m
    }
  }
  if(method=="sum"){
    for (i in 1:length(cluster_idx)) {
      x<-data_au[data_au[,cluster]==cluster_idx[i],]
      x$clusterXtp<-NULL
      m<-colSums(x[,1:n])
      list_m_clus[[i]]<-m
    }
  }
  
  names(list_m_clus)<-cluster_idx
  
  new_data<-rbind(list_m_clus[[1]],list_m_clus[[2]])
  for (i in 3:length(list_m_clus)) {
    new_data<-rbind(new_data,list_m_clus[[i]])
  }
  new_data<-as.data.frame(new_data)
  new_data$clusters<-cluster_idx
  
  tp<-c()
  for (i in 1:nrow(new_data)) {
    t<-strsplit(new_data$clusters[i], "[_]")[[1]][1]
    tp<-append(tp,t)
  }
  new_data$time_point<-tp

  return(new_data)
}
